export type { Artist, SimplifiedArtist } from './model/types'
export { artistQueries } from './api/queries'
export { getTopArtists } from './api/requests'
export type { ArtistCountries } from './api/countries'
export { aggregateGenres, genreIndex, genresOf } from './lib/genres'
export { ArtistCard } from './ui/ArtistCard'
