/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppAlbumsRouteImport } from './routes/_app/albums'
import { Route as AppArtistsRouteImport } from './routes/_app/artists'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppRankRouteImport } from './routes/_app/rank'
import { Route as AppRecentRouteImport } from './routes/_app/recent'
import { Route as AppTracksRouteImport } from './routes/_app/tracks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlbumsRoute = AppAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistsRoute = AppArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppRankRoute = AppRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentRoute = AppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksRoute = AppTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/albums': typeof AppAlbumsRoute
  '/artists': typeof AppArtistsRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/rank': typeof AppRankRoute
  '/recent': typeof AppRecentRoute
  '/tracks': typeof AppTracksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/albums': typeof AppAlbumsRoute
  '/artists': typeof AppArtistsRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/rank': typeof AppRankRoute
  '/recent': typeof AppRecentRoute
  '/tracks': typeof AppTracksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_app/albums': typeof AppAlbumsRoute
  '/_app/artists': typeof AppArtistsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/rank': typeof AppRankRoute
  '/_app/recent': typeof AppRecentRoute
  '/_app/tracks': typeof AppTracksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/albums'
    | '/artists'
    | '/dashboard'
    | '/history'
    | '/rank'
    | '/recent'
    | '/tracks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/albums'
    | '/artists'
    | '/dashboard'
    | '/history'
    | '/rank'
    | '/recent'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/callback'
    | '/_app/albums'
    | '/_app/artists'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/rank'
    | '/_app/recent'
    | '/_app/tracks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/albums': {
      id: '/_app/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AppAlbumsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artists': {
      id: '/_app/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AppArtistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rank': {
      id: '/_app/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof AppRankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recent': {
      id: '/_app/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AppRecentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracks': {
      id: '/_app/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AppTracksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlbumsRoute: typeof AppAlbumsRoute
  AppArtistsRoute: typeof AppArtistsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRankRoute: typeof AppRankRoute
  AppRecentRoute: typeof AppRecentRoute
  AppTracksRoute: typeof AppTracksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlbumsRoute: AppAlbumsRoute,
  AppArtistsRoute: AppArtistsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRankRoute: AppRankRoute,
  AppRecentRoute: AppRecentRoute,
  AppTracksRoute: AppTracksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
